server:
  port: 1122
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhpie/config-server.git
          search-paths: C:\IdeaProjects\reactive-yaml-gen\src\main\resources
  application:
    name: service-a
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
    web:
      servlet:
        context-path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        r2dbc: DEBUG
debug: true


management:
  endpoints:
    web:
      exposure:
        include: refresh

target:
  directory: C:\\IdeaProjects\\reactive-yaml-gen\\src\\main\\resources\\

temp-path: C:\result